# Generated by Django 5.1.6 on 2025-02-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('Admin', 'Admin'), ('Sponsor', 'Sponsor'), ('Driver', 'Driver')], max_length=20)),
                ('account_username', models.CharField(max_length=150, unique=True)),
                ('account_password', models.CharField(max_length=150)),
            ],
        ),
    ]
