# Generated by Django 5.1.6 on 2025-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutData",
            fields=[
                (
                    "teamnum",
                    models.IntegerField(blank=True, db_column="teamNum", null=True),
                ),
                (
                    "versionnum",
                    models.IntegerField(
                        db_column="versionNum", primary_key=True, serialize=False
                    ),
                ),
                (
                    "releasedate",
                    models.DateField(blank=True, db_column="releaseDate", null=True),
                ),
                (
                    "productname",
                    models.CharField(
                        blank=True, db_column="productName", max_length=100, null=True
                    ),
                ),
                (
                    "productdesc",
                    models.CharField(
                        blank=True, db_column="productDesc", max_length=300, null=True
                    ),
                ),
            ],
            options={
                "db_table": "about_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FName", models.CharField(max_length=100)),
                ("LName", models.CharField(max_length=100)),
            ],
        ),
    ]
