# Generated by Django 5.1.6 on 2025-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutdata_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_username', models.CharField(max_length=150, unique=True)),
                ('driver_points', models.IntegerField(default=0)),
                ('driver_email', models.CharField(max_length=150)),
            ],
        ),
    ]
