# Generated by Django 5.1.6 on 2025-03-11 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('PointsChange', models.IntegerField()),
                ('PointsReason', models.CharField(max_length=255)),
                ('PointsDate', models.DateField()),
                ('DriverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.driver')),
            ],
        ),
    ]
